/* eslint-disable */
/* tslint:disable */
/* auto-generated vue proxies */
import { defineContainer } from './vue-component-lib/utils';

import type { JSX } from '@revolist/revogrid';




export const RevoGrid = /*@__PURE__*/ defineContainer<JSX.RevoGrid>('revo-grid', undefined, [
  'rowHeaders',
  'frameSize',
  'rowSize',
  'colSize',
  'range',
  'readonly',
  'resize',
  'canFocus',
  'useClipboard',
  'columns',
  'source',
  'pinnedTopSource',
  'pinnedBottomSource',
  'rowDefinitions',
  'editors',
  'applyOnClose',
  'plugins',
  'columnTypes',
  'theme',
  'rowClass',
  'autoSizeColumn',
  'filter',
  'focusTemplate',
  'canMoveColumns',
  'trimmedRows',
  'exporting',
  'grouping',
  'stretch',
  'additionalData',
  'disableVirtualX',
  'disableVirtualY',
  'hideAttribution',
  'jobsBeforeRender',
  'registerVNode',
  'accessible',
  'contentsizechanged',
  'beforeedit',
  'beforerangeedit',
  'afteredit',
  'beforeautofill',
  'beforerange',
  'afterfocus',
  'roworderchanged',
  'beforesortingapply',
  'beforesorting',
  'rowdragstart',
  'headerclick',
  'beforecellfocus',
  'beforefocuslost',
  'beforesourceset',
  'beforeanysource',
  'aftersourceset',
  'afteranysource',
  'beforecolumnsset',
  'beforecolumnapplied',
  'aftercolumnsset',
  'beforefilterapply',
  'beforefiltertrimmed',
  'beforetrimmed',
  'aftertrimmed',
  'viewportscroll',
  'beforeexport',
  'beforeeditstart',
  'aftercolumnresize',
  'beforerowdefinition',
  'filterconfigchanged',
  'rowheaderschanged',
  'beforegridrender',
  'aftergridinit',
  'additionaldatachanged',
  'afterthemechanged'
]);

